# Alertmanager configuration for ProbNeural Operator Lab

global:
  # Global configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@probneural-lab.com'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'
  - match:
      alertname: ModelPerformanceDegradation
    receiver: 'ml-team-alerts'
  - match:
      alertname: UncertaintyCalibrationDrift
    receiver: 'ml-team-alerts'

# Receivers configuration
receivers:
- name: 'default'
  email_configs:
  - to: 'admin@probneural-lab.com'
    subject: '[ProbNeural] Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'critical-alerts@probneural-lab.com'
    subject: '[CRITICAL] ProbNeural Alert: {{ .GroupLabels.alertname }}'
    body: |
      🚨 CRITICAL ALERT 🚨
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}
      
      Please investigate immediately!
  
  slack_configs:
  - channel: '#critical-alerts'
    color: 'danger'
    title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Instance:** {{ .Labels.instance }}
      **Severity:** {{ .Labels.severity }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'warnings@probneural-lab.com'
    subject: '[WARNING] ProbNeural Alert: {{ .GroupLabels.alertname }}'
    
  slack_configs:
  - channel: '#alerts'
    color: 'warning'
    title: '⚠️ Warning: {{ .GroupLabels.alertname }}'

- name: 'ml-team-alerts'
  email_configs:
  - to: 'ml-team@probneural-lab.com'
    subject: '[ML ALERT] {{ .GroupLabels.alertname }}'
    body: |
      🤖 ML System Alert
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Model: {{ .Labels.model_name | default "unknown" }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      {{ end }}
      
      Please check model performance and retrain if necessary.
  
  slack_configs:
  - channel: '#ml-alerts'
    color: 'warning'
    title: '🤖 ML Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Model:** {{ .Labels.model_name | default "unknown" }}
      {{ end }}

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

- source_match:
    alertname: 'ServiceDown'
  target_match_re:
    alertname: '(HighErrorRate|HighLatency|HighMemoryUsage)'
  equal: ['instance']