name: Terragon Quality Gates
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 2 * * *
jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -e .[dev,test]
    - name: Run Quality Gates - Generation 1
      run: python terragon/quality_gates/quality_gates.py gen1
    - name: Run Quality Gates - Generation 2
      run: python terragon/quality_gates/quality_gates.py gen2
      if: success()
    - name: Run Quality Gates - Generation 3
      run: python terragon/quality_gates/quality_gates.py gen3
      if: success()
    - name: Run Research Quality Gates
      run: python terragon/quality_gates/quality_gates.py research
      if: success()
    - name: Upload Quality Reports
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: .terragon/reports/
      if: always()